# Generated by Django 3.2.13 on 2022-06-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staticwebapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
