# Generated by Django 3.2.13 on 2022-06-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staticwebapp', '0004_auto_20220622_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='img1',
            new_name='imgs',
        ),
    ]
